<img height="60px" src="https://colab.research.google.com/img/colab_favicon.ico" align="left" hspace="20px" vspace="5px">

<h1>ArasNet</h1>
<h1>Evolving CNN for unstructured data stream<h1>
Optimize CNN, optimize output layer and freeze CNN, optimize FC layer and freeze CNN

In [1]:
import numpy as np
import math as mt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time 
import os    
import copy
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
from numpy import linalg as LA
import matplotlib.pyplot as plt
from mainAutocnnBatchNorm import autocnn2
from sklearn.model_selection import train_test_split

In [ ]:
# prepare data
print('==> Preparing the data')
classes     = 10
no_of_epoch = 1000
train_data=torch.load('data/train_data.pt')
train_label=torch.load('data//train_label.pt')
test_data=torch.load('data//test_data.pt')
test_label=torch.load('data//test_label.pt')
x_train = torch.tensor(train_data,dtype=torch.float64)
y_train = torch.tensor(train_label,dtype=torch.int64)
nData,_,_,_ = x_train.shape
shuffled_indices = torch.randperm(nData)
nTraining = 0.9*nData
x_train = x_train[shuffled_indices]
y_train = y_train[shuffled_indices]
x_val = x_train[int(0.9*nData):nData+1]
y_val = y_train[int(0.9*nData):nData+1]
#x_train = x_train[0:int(0.9*nData)]
#y_train = y_train[0:int(0.9*nData)]
x_test = torch.tensor(test_data,dtype=torch.float64)
y_test = torch.tensor(test_label,dtype=torch.int64)
print(x_train.shape, y_train.shape)
print(x_val.shape, y_val.shape)
print(x_test.shape, y_test.shape)

==> Preparing the data
torch.Size([50000, 3, 32, 32]) torch.Size([50000])
torch.Size([5000, 3, 32, 32]) torch.Size([5000])
torch.Size([10000, 3, 32, 32]) torch.Size([10000])


In [ ]:
(ArAsNet, fccLayerEvo, convLayerEvo, Bias2, Var, convFeatureCorr, Error_test, Error_val, Error_train,
           Loss_test, Loss_val, Loss_train, Iter) = autocnn2(x_train, y_train, x_val, y_val, x_test, y_test, 
                                                         no_of_epoch, gpu = 'cuda:1')


==> Epoch: 1
------------IN VALIDATION PHASE------------
Validation Error: 90.29296875
Validation Loss: 2.3036387869224297
-------------------------------------------
reset minimum
convCorrelationScore :  0.9927433244095987
epoch > 2 :  False
ns.retrainCounter :  0
len(q) :  0
Accomodate CNN layers
=====**** Data point :  0
miustd_NS :  0.291227578573809 | miustdmin_NS :  0.291227578573809
miustd_NHS :  0.2845618442239097 | miustdmin_NHS :  0.2845618442239097
------------IN TRAINING PHASE------------
Training Error: 78.91464193763636
Training Loss: 2.2417094642341575
Training Time: 10.27756929397583
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 78.39200949367088
Testing Loss: 2.2393123188457698
Confussion Matrix: [[233  81  22  17 114  23   4 128  53 325]
 [ 29 349  26   8 231  31   6  84  15 221]
 [ 64  47  21  18 474  33  11 215  10 107]
 [ 21  52  24  11 346 129  22 245  18 132]
 [ 18  29   5   8 635  50   6 166  22  61]
 [ 1

------------IN TRAINING PHASE------------
Training Error: 74.53324808489026
Training Loss: 2.19899457470032
Training Time: 10.109843730926514
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 74.35719936708861
Testing Loss: 2.1973084149181044
Confussion Matrix: [[273  86   1   7  60  43   3 184  16 327]
 [ 29 442   4   2 101  88   5  93   4 232]
 [ 72  43  10   2 375 167   3 245   5  78]
 [ 31  49   8   4 174 395   2 210   1 126]
 [ 27  26   4   1 533 146   3 199   3  58]
 [ 23  52   5   4 245 361   5 204   0 101]
 [ 11  23   5   2 471 214   7 189   0  78]
 [ 15  42   2   4 218 139   2 490   1  87]
 [133 152   4  15  24  63   3  91  33 482]
 [ 29 209   2   9  58  81   2 199   6 405]]
Testing Time: 2.2939300537109375
-------------------------------------------

==> Epoch: 9
------------IN VALIDATION PHASE------------
Validation Error: 72.578125
Validation Loss: 2.1907436343938445
-------------------------------------------
update_mini

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 68.99256712335455
Training Loss: 2.124471614808713
Training Time: 14.404563188552856
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 68.42365506329115
Testing Loss: 2.123075095955896
Confussion Matrix: [[789  14   7   1  41   7  14  47  14  66]
 [206 226   8   0  47  21  59  43  27 363]
 [259   8  21   2 445  20 102 104  16  23]
 [216  15  41   6 212  78 218 122  37  55]
 [162   5  31   0 544  14  78 143  13  10]
 [175  13  38   4 282  92 187 138  39  32]
 [102  11  24   4 357  29 317  92  25  39]
 [156  12  12   2 170  26  58 469  20  75]
 [704  26  10   1  36  11  17  17  40 138]
 [176  51   4   0  26   6  25  42  23 647]]
Testing Time: 1.3437857627868652
-------------------------------------------

==> Epoch: 13
------------IN VALIDATION PHASE------------
Validation Error: 69.08203125
Validation Loss: 2.1232840028536417
-------------------------------------------
reset mi

------------IN VALIDATION PHASE------------
Validation Error: 59.4140625
Validation Loss: 2.036620828755954
-------------------------------------------
update_minimum
convCorrelationScore :  0.5750049503539993
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.0965623394838796
RHS :  0.015614005591002242
Cond4 :  False
Accomodate CNN layers
------------IN TRAINING PHASE------------
Training Error: 59.45092710997443
Training Loss: 2.0524153181110214
Training Time: 13.79207468032837
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 59.94857594936709
Testing Loss: 2.0549661590289148
Confussion Matrix: [[766  18  15   0  42   9  42  36   8  64]
 [101 448  10   1  29  14  70  33  11 283]
 [228  10  66  14 283  37 248  76  17  21]
 [147  21  32  42  99 144 350  87  21  57]
 [113   8  34   6 432  28 239 118   7  15]
 [111   9  50  38 155 214 266 118  11  28]
 [ 78   7   7   9 106  14 720  22   3  34]
 [ 84   8  15   9  96  41 

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 62.959159213258786
Training Loss: 1.9791125894701602
Training Time: 15.621052980422974
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 62.75712025316456
Testing Loss: 1.977599123342119
Confussion Matrix: [[615   5   0  35  21   2  82   0 113 127]
 [ 60  93   0  13   4   1 140   0  57 632]
 [129   0   0 149 237   8 381   0  27  69]
 [ 50   4   0 318  57  15 453   0  17  86]
 [ 66   3   0  94 363   2 421   0  21  30]
 [ 31   2   0 426 101  27 326   0  23  64]
 [  8   1   0  19  25   0 922   0   4  21]
 [ 74   7   0 179 197  29 266   1  12 235]
 [200  13   0  14   4   6  77   0 480 206]
 [ 31   3   0  11   2   0  42   0  27 884]]
Testing Time: 1.4226205348968506
-------------------------------------------

==> Epoch: 21
------------IN VALIDATION PHASE------------
Validation Error: 61.77734375
Validation Loss: 1.9673616379815904
-------------------------------------------
reset 

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 52.585517902813294
Training Loss: 1.7428489150700637
Training Time: 18.168405055999756
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 52.78876582278481
Testing Loss: 1.7492524093782673
Confussion Matrix: [[669  44 138   0  10   2  87   2   5  43]
 [ 45 773  11   0   9   0  98   4   0  60]
 [ 49  13 458   1  66  43 353   6   0  11]
 [ 22  28 115   2  49 150 603  11   1  19]
 [ 20  11 104   1 328  12 499  22   0   3]
 [ 15  15 139   1  57 316 424  27   0   6]
 [  2   2  30   0   5   4 956   1   0   0]
 [ 18  18  82   1  95  76 255 432   0  23]
 [322 190  66   0  15   4 169   1 148  85]
 [ 67 131   8   0  12   4 143   5   1 629]]
Testing Time: 1.7286450862884521
-------------------------------------------

==> Epoch: 26
------------IN VALIDATION PHASE------------
Validation Error: 51.77734375000001
Validation Loss: 1.7258706168633047
-------------------------------------------

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 40.94229538727294
Training Loss: 1.6239050543493903
Training Time: 22.949060201644897
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 41.811708860759495
Testing Loss: 1.6418544479833292
Confussion Matrix: [[524  63 148  29  39   3  81   2  40  71]
 [  4 803  19   4   8   1  64   3   1  93]
 [ 38   6 658  42  76  19 140   9   5   7]
 [  5  14 139 435  66  61 251  14   5  10]
 [ 11   6 178  55 531  15 176  26   1   1]
 [  2   9 171 308  71 272 135  23   1   8]
 [  3   1  62  35  20   2 876   1   0   0]
 [  3   9 143  48 123  47  80 526   0  21]
 [ 79 192  52  51  35   6  96   1 408  80]
 [ 10  97  15  15  10   4  53   4   4 788]]
Testing Time: 2.2315726280212402
-------------------------------------------

==> Epoch: 31
------------IN VALIDATION PHASE------------
Validation Error: 40.0
Validation Loss: 1.6163191184220178
-------------------------------------------
reset minimu

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 37.21387467116041
Training Loss: 1.5566741011536973
Training Time: 27.641144037246704
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 37.42088607594937
Testing Loss: 1.5748243235565536
Confussion Matrix: [[454  68 107   8  41  22  55   4 232   9]
 [  1 928   4   1   5   5  24   3  23   6]
 [ 18   9 435  13 142 158 190   6  28   1]
 [  7  23  32 180  89 401 221   9  36   2]
 [  6   5  35   5 717  58 136  20  18   0]
 [  2   5  21  24  68 755  89  18  18   0]
 [  0   5  16   8  32  38 895   0   6   0]
 [  9  17  26   4 151 169  60 549  10   5]
 [  6  54  18   5   4  16  27   3 864   3]
 [ 16 260   6   5  25  23  83  19  89 474]]
Testing Time: 2.229811906814575
-------------------------------------------

==> Epoch: 36
------------IN VALIDATION PHASE------------
Validation Error: 37.05078125
Validation Loss: 1.5486243128183368
-------------------------------------------
reset m

------------IN VALIDATION PHASE------------
Validation Error: 32.6171875
Validation Loss: 1.440244794556997
-------------------------------------------
reset minimum
convCorrelationScore :  0.4921305957958883
epoch > 2 :  True
ns.retrainCounter :  3
len(q) :  10
LHS < :  0.12768837781079595
RHS :  0.007411210750793721
Cond4 :  False
Accomodate CNN layers
------------IN TRAINING PHASE------------
Training Error: 30.310102298741448
Training Loss: 1.438698988687195
Training Time: 28.044676303863525
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 32.42681962025317
Testing Loss: 1.477595628413041
Confussion Matrix: [[561   8 104   6  59  13  28   8 201  12]
 [ 10 805   6   1  13   6  37   2  94  26]
 [ 32   1 625  19 110  61 128   1  22   1]
 [  4   5  86 297 148 232 189   9  29   1]
 [  4   1  52   6 817  17  90   3  10   0]
 [  1   1  50  43 117 658 102  14  14   0]
 [  1   0  33   8  31  11 909   0   7   0]
 [  5   0  56  12 224  88 

------------IN VALIDATION PHASE------------
Validation Error: 26.73828125
Validation Loss: 1.3967121954454709
-------------------------------------------
reset minimum
convCorrelationScore :  0.4934452630633227
epoch > 2 :  True
ns.retrainCounter :  1
len(q) :  10
LHS < :  0.04463563312846852
RHS :  0.007431008902482237
Cond4 :  False
Accomodate CNN layers
------------IN TRAINING PHASE------------
Training Error: 28.26326725732945
Training Loss: 1.4000263333386676
Training Time: 27.868340969085693
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 31.269778481012654
Testing Loss: 1.4549276272159757
Confussion Matrix: [[588  20 113   4  63   5  38  11 151   7]
 [  3 902   5   1   5   3  29   2  27  23]
 [ 23   1 605   7 121  60 161   4  17   1]
 [  5  10  76 210 141 218 288  20  28   4]
 [  7   2  23   3 796  17 137   8   7   0]
 [  1   1  34  21 107 675 126  25  10   0]
 [  0   1  14   2  22   9 946   1   5   0]
 [  7   5  36   3 144 

A new CNN layer is created


------------IN TRAINING PHASE------------
Training Error: 36.130115092562896
Training Loss: 1.9110551590160414
Training Time: 37.24714946746826
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 37.96479430379747
Testing Loss: 1.9294424698970567
Confussion Matrix: [[545   8 199  16  11   2  50  24 135  10]
 [ 19 687  24   2   2   4  95  20  69  78]
 [ 24   0 754  14  12  10 157  18  11   0]
 [  5   0 171 300  32  44 396  28  19   5]
 [ 10   1 232  14 380   6 313  37   7   0]
 [  2   0 150 120  31 315 313  55  14   0]
 [  2   0  54   9   2   1 919   4   9   0]
 [  3   2  78  25  39  13 100 731   4   5]
 [ 18   8  56   1   2   1  17   5 887   5]
 [ 29  33  35  11   6   5 128  29  53 671]]
Testing Time: 2.490400552749634
-------------------------------------------

==> Epoch: 51
------------IN VALIDATION PHASE------------
Validation Error: 36.38671875
Validation Loss: 1.8957660990606313
-------------------------------------------
reset m

------------IN VALIDATION PHASE------------
Validation Error: 29.062500000000004
Validation Loss: 1.779717733403149
-------------------------------------------
update_minimum
convCorrelationScore :  0.28620980346302516
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.1259648946268036
RHS :  0.004310159113308785
Cond4 :  False
Accomodate CNN layers
------------IN TRAINING PHASE------------
Training Error: 33.77517582205555
Training Loss: 1.837397602345276
Training Time: 37.352803468704224
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 36.263844936708864
Testing Loss: 1.8713067531125425
Confussion Matrix: [[618   9 148   9  17   1  17   8 168   5]
 [ 15 735  25   2   1   5  25   6 153  33]
 [ 38   0 842   9  16   7  65   7  16   0]
 [ 15   3 257 384  45  33 202  21  37   3]
 [ 17   0 304  14 461   4 163  25  12   0]
 [  9   2 223 139  64 278 208  45  32   0]
 [  3   0  94   9  11   1 862   4  15   1]
 [ 10   0 143  2

------------IN TRAINING PHASE------------
Training Error: 21.026214827661928
Training Loss: 0.8446645105688625
Training Time: 38.584561347961426
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 24.604430379746837
Testing Loss: 0.9401274241322646
Confussion Matrix: [[684  14  47  16  37   6  13  21 107  55]
 [  8 786   3   6   3   5  19   3  37 130]
 [ 32   1 597  26 108  73 102  35  19   7]
 [  8   1  38 451  79 207 114  44  30  28]
 [  6   0  24  26 768  22  84  59   9   2]
 [  1   0  13  75  75 715  46  56   7  12]
 [  1   0  15  23  35  24 887   5   7   3]
 [  8   2  10  15  34  54  16 838   4  19]
 [ 19  13   8   4   6   6   2   6 916  20]
 [ 12  28   4   5   3   7  10  10  23 898]]
Testing Time: 2.6925978660583496
-------------------------------------------

==> Epoch: 64
------------IN VALIDATION PHASE------------
Validation Error: 20.48828125
Validation Loss: 0.8301089978385114
-------------------------------------------
Grow

------------IN VALIDATION PHASE------------
Validation Error: 17.109375
Validation Loss: 0.7018206932621462
-------------------------------------------
Grow FC Layer condition ==>
condition1 : 0.2098163676520457 condition2 :  0.18290818382602286
Grow FC Layer condition ==>
condition1 : 0.19967746830680816 condition2 :  0.19610818382602285
Grow FC Layer condition ==>
condition1 : 0.19518576918227565 condition2 :  0.19437485049268954
NOT Allowed to grow FCLayer
update_minimum
convCorrelationScore :  0.22598464643754745
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.08398190248672388
RHS :  0.003403202027062961
Cond4 :  False
Accomodate ALL layers without evolution
------------IN TRAINING PHASE------------
Training Error: 19.013746803069054
Training Loss: 0.7392939709075675
Training Time: 37.628289222717285
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 23.615506329113924
Testing Loss: 0.862892301242081
Confussion M

Validation Error: 18.45703125
Validation Loss: 0.9809406013104832
-------------------------------------------
NOT Allowed to grow FCLayer
reset minimum
convCorrelationScore :  0.2354328116499049
epoch > 2 :  True
ns.retrainCounter :  2
len(q) :  10
LHS < :  0.07453373727436644
RHS :  0.0035454860959570245
Cond4 :  False
Accomodate FC layers
------------IN TRAINING PHASE------------
Training Error: 17.404891295201335
Training Loss: 0.8011496117609176
Training Time: 40.34970569610596
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 23.012262658227847
Testing Loss: 0.9284670340435727
Confussion Matrix: [[744  13  44  11  30   6  33  11  65  43]
 [  3 853   7   2   4   2  30   2  23  74]
 [ 33   0 663  20  82  39 136  14  10   3]
 [ 10   3  43 472  79 159 185  21  10  18]
 [  5   1  39  19 807  13  91  21   4   0]
 [  5   0  27  81  83 680  87  35   1   1]
 [  1   0  12   6  21   3 951   1   4   1]
 [  8   2  18  24 103  35  38 761   1 

------------IN VALIDATION PHASE------------
Validation Error: 17.1875
Validation Loss: 0.6708865331221918
-------------------------------------------
Grow FC Layer condition ==>
condition1 : 0.2076163676520457 condition2 :  0.18850818382602286
Grow FC Layer condition ==>
condition1 : 0.19747746830680815 condition2 :  0.17970818382602283
Grow FC Layer condition ==>
condition1 : 0.19298576918227564 condition2 :  0.18664151715935617
NOT Allowed to grow FCLayer
update_minimum
convCorrelationScore :  0.2347656697294439
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.07520087919482743
RHS :  0.003535439312815591
Cond4 :  False
Accomodate FC layers
------------IN TRAINING PHASE------------
Training Error: 16.319133634762387
Training Loss: 0.6569238788174953
Training Time: 40.06847262382507
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 22.1123417721519
Testing Loss: 0.8082157383428745
Confussion Matrix: [[741  11  55  14

------------IN TRAINING PHASE------------
Training Error: 23.60853580257777
Training Loss: 0.8539215646794428
Training Time: 41.26258301734924
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 28.79746835443038
Testing Loss: 0.9902635650042462
Confussion Matrix: [[774  11  53  19   0   3  29  13  64  34]
 [  6 851   8   6   0   3  27   2  28  69]
 [ 43   0 725  34   0  39 135  13  11   0]
 [ 17   2  62 538   0 154 183  20  16   8]
 [447   1 124 107   0  41 222  44   9   5]
 [ 15   0  38 100   0 703 102  38   2   2]
 [  5   0  12  17   0   2 958   1   4   1]
 [ 17   2  28  36   0  45  42 820   1   9]
 [ 22  11  14  14   0   4  17   0 910   8]
 [ 17  29   8  14   0  10  32   8  31 851]]
Testing Time: 2.905301570892334
-------------------------------------------

==> Epoch: 86
------------IN VALIDATION PHASE------------
Validation Error: 24.140625
Validation Loss: 0.8465717413746336
-------------------------------------------
NOT Allowe

------------IN VALIDATION PHASE------------
Validation Error: 23.6328125
Validation Loss: 0.8082320054447152
-------------------------------------------
NOT Allowed to grow FCLayer
update_minimum
convCorrelationScore :  0.22933023753279919
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.08063631139147215
RHS :  0.003453584752511661
Cond4 :  False
Accomodate FC layers
------------IN TRAINING PHASE------------
Training Error: 24.169197564234818
Training Loss: 0.8331329733601343
Training Time: 40.5274612903595
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 29.667721518987346
Testing Loss: 0.9787849641095482
Confussion Matrix: [[778  11  39  15   0   3  34  13  67  40]
 [  6 841   6   2   0   2  31   2  28  82]
 [ 56   0 690  30   0  39 153  16  13   3]
 [ 20   2  50 504   0 135 229  20  19  21]
 [511   1  91  70   0  24 247  45   9   2]
 [ 20   0  33 104   0 653 140  41   4   5]
 [  3   0   7  10   0   2 972   1   4 

Testing Error: 23.68473101265823
Testing Loss: 0.8466755065284712
Confussion Matrix: [[715  13  53  20  46   2  25   8  80  38]
 [  6 791   7   1   3   5  32   2  31 122]
 [ 25   0 638  45 110  44 119   6  12   1]
 [ 10   2  52 535  74 178 115  13  12   9]
 [  2   0  26  25 827  14  80  17   9   0]
 [  1   1  23 107  84 715  49  15   3   2]
 [  1   0  12  24  32  12 914   0   4   1]
 [  7   2  23  47 117  50  28 716   3   7]
 [ 18  10  11  11   9   3  12   2 914  10]
 [ 15  20   9  15  10   9  34   3  24 861]]
Testing Time: 2.7440900802612305
-------------------------------------------

==> Epoch: 99
------------IN VALIDATION PHASE------------
Validation Error: 17.578125
Validation Loss: 0.6852618858964062
-------------------------------------------
NOT Allowed to grow FCLayer
update_minimum
convCorrelationScore :  0.24913061547480825
epoch > 2 :  True
ns.retrainCounter :  0
len(q) :  10
LHS < :  0.06083593344946309
RHS :  0.003751767338855996
Cond4 :  False
Accomodate ALL layers
-----

------------IN VALIDATION PHASE------------
Validation Error: 19.296875
Validation Loss: 0.7366825007046138
-------------------------------------------
NOT Allowed to grow FCLayer
reset minimum
convCorrelationScore :  0.2594166128767361
epoch > 2 :  True
ns.retrainCounter :  2
len(q) :  10
LHS < :  0.050549936047535216
RHS :  0.00390666869060902
Cond4 :  False
Accomodate ALL layers
------------IN TRAINING PHASE------------
Training Error: 22.746962918649853
Training Loss: 0.8222554645022289
Training Time: 41.842244148254395
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 27.80854430379747
Testing Loss: 0.9680950403560722
Confussion Matrix: [[710  15  49   0  43  13  24  15  77  54]
 [  4 849   4   0   0   2  22   6  35  78]
 [ 29   0 676   0  50  49 159  11  15  11]
 [205   4  74   0  85 274 280  30  26  22]
 [  5   1  60   0 703  18 188  17   6   2]
 [ 14   3  45   0  48 705 126  42   7  10]
 [  3   0   8   0  10  10 959   1   6  

Testing Error: 25.11867088607595
Testing Loss: 1.0832642914186899
Confussion Matrix: [[718  19  35   3  35   3   6  15 117  49]
 [  2 852   5   1   2   1   7   0  51  79]
 [ 44   3 702   6  82  47  65  14  31   6]
 [ 21   3  88 347 128 118 160  29  67  39]
 [  6   0  52   7 835   8  60  17  10   5]
 [  8   4  52  60 115 570  71  52  48  20]
 [  4   1  36   1  38   8 885   2  20   5]
 [  9   1  27   7 107  25  16 768  20  20]
 [ 11   8  11   0   6   0   4   0 944  16]
 [ 15  33   4   3   3   2   7   6  32 895]]
Testing Time: 2.880117893218994
-------------------------------------------

==> Epoch: 112
------------IN VALIDATION PHASE------------
Validation Error: 18.92578125
Validation Loss: 0.926688688508593
-------------------------------------------
reset minimum
convCorrelationScore :  0.2558335046254882
epoch > 2 :  True
ns.retrainCounter :  2
len(q) :  10
LHS < :  0.05413304429878313
RHS :  0.0038527090900075567
Cond4 :  False
Accomodate ALL layers
------------IN TRAINING PHASE----

------------IN TRAINING PHASE------------
Training Error: 14.116847819989294
Training Loss: 0.5866563259020612
Training Time: 41.06864023208618
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 22.596914556962027
Testing Loss: 0.8048666699830809
Confussion Matrix: [[747   9  54  22  38   0  21   9  76  24]
 [  7 846   8   7   1   2  21   1  43  64]
 [ 38   0 724  33  58  30 100   8   7   2]
 [ 11   5  63 589  63  81 146  15  17  10]
 [  3   0  53  39 794   9  89   7   5   1]
 [  3   0  48 189  64 578  85  28   3   2]
 [  1   0  16  22  14   3 939   1   3   1]
 [  8   0  33  40 105  19  30 755   4   6]
 [ 20   8  16  15   6   0   9   1 918   7]
 [ 22  37  11  22   7   4  22   4  32 839]]
Testing Time: 2.674692153930664
-------------------------------------------

==> Epoch: 119
------------IN VALIDATION PHASE------------
Validation Error: 13.92578125
Validation Loss: 0.5762892916519883
-------------------------------------------
updat

------------IN TRAINING PHASE------------
Training Error: 9.866128507477548
Training Loss: 0.4628565332574302
Training Time: 41.16770648956299
-------------------------------------------
------------IN Testing PHASE---------------
Testing Error: 20.055379746835442
Testing Loss: 0.7284982855984976
Confussion Matrix: [[786   8  41  13  22   4   9  14  84  19]
 [  7 878   4   3   2   1   8   1  43  53]
 [ 40   2 738  31  73  42  47  10  13   4]
 [ 14   3  55 574  88 135  49  32  35  15]
 [  5   1  49  26 844  17  25  21  12   0]
 [  7   3  32 106  73 702  13  46  15   3]
 [  2   1  40  42  27  19 846   4  17   2]
 [  8   1  27  31  66  26   3 826   7   5]
 [ 23   5   9   7   3   0   2   2 941   8]
 [ 19  36   6   8   6   7   6   6  48 858]]
Testing Time: 2.6290552616119385
-------------------------------------------

==> Epoch: 126
------------IN VALIDATION PHASE------------
Validation Error: 10.0
Validation Loss: 0.4564866331911099
-------------------------------------------
update_minim

In [ ]:
ArAsNet

In [ ]:
SMALL_SIZE = 12
MEDIUM_SIZE = 14
BIGGER_SIZE = 16

plt.rc('font', size=8)                   # controls default text sizes
plt.rc('axes', titlesize=BIGGER_SIZE)    # fontsize of the axes title
plt.rc('axes', labelsize=MEDIUM_SIZE)    # fontsize of the x and y labels
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('legend', fontsize=SMALL_SIZE)    # legend fontsize
plt.rc('figure', titlesize=BIGGER_SIZE)  # fontsize of the figure title

In [ ]:
fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(22, 14))

ax1 = axes[0,0]
ax2 = axes[0,1]
ax3 = axes[0,2]
ax4 = axes[1,0]
ax5 = axes[1,1]
ax6 = axes[1,2]

ax1.plot(Iter[0:len(convFeatureCorr)],convFeatureCorr,'k-')
ax1.set_title('Feature Convolution Score')
ax1.set_ylabel('$FCS$')
ax1.set_xlabel('Number of epochs')
ax1.yaxis.tick_right()
ax1.autoscale_view('tight')

ax2.plot(Iter[0:len(convLayerEvo)],convLayerEvo[0:len(convLayerEvo)],'k-')
ax2.set_title('Convolutional Stage Evolution')
ax2.set_ylabel('Number of Convolutional Stages')
ax2.set_xlabel('Number of epochs')
ax2.yaxis.tick_right()
ax2.autoscale_view('tight')

ax3.plot(Iter[0:len(Error_train)],Error_train,'g--', label='Training Error')
ax3.plot(Iter[0:len(Error_val)],Error_val,'r-.', label='Validation Error')
ax3.plot(Iter[0:len(Error_test)],Error_test,'k-', label='Testing Error')
ax3.legend(loc=(0.5, 0.6))
ax3.yaxis.tick_right()
ax3.set_title('Error of Training, Validation and Testing Phases')
ax3.set_ylabel('$\%$ of Error')
ax3.set_xlabel('Number of epochs')
ax3.autoscale_view('tight')

ax4.plot(Iter[0:len(Bias2)],Bias2,'k-', label='Bias')
ax4.plot(Iter[0:len(Var)],Var,'r--', label='Variance')
ax4.legend(loc=(0.6, 0.1))
ax4.set_ylabel('$Bias-Var$ Level')
ax4.set_title('Bias and Variance')
ax4.set_xlabel('Number of epochs')
ax4.yaxis.tick_right()
ax4.autoscale_view('tight')

ax5.plot(Iter[0:len(fccLayerEvo)],fccLayerEvo[0:len(fccLayerEvo)], 'k-')
ax5.set_title('Fully Connected Layer Evolution')
ax5.set_ylabel('Number of Fully Connected Layers')
ax5.set_xlabel('Number of epochs')
ax5.yaxis.tick_right()
ax5.autoscale_view('tight')

#ax6.plot(Iter[0:len(layer1)],layer1,'y-', label='$1^{st}$ layer')
#ax6.plot(Iter[0:len(layer2)],layer2,'r-.', label='$2^{nd}$ layer')
#ax6.plot(Iter[0:len(layer2)],layer3,'c-.', label='$3^{rd}$ layer')
ax6.set_title('Hidden Node Evolution')
ax6.set_ylabel('Number of Fully Hidden Nodes')
ax6.set_xlabel('Number of epochs')
ax6.legend(loc=(0.65, 0.1))
ax6.yaxis.tick_right()
ax6.autoscale_view('tight')

In [ ]:
without delete FC layer